#!/usr/bin/env node
// config/destinations.json を生成する。CDC の目的地一覧（244件）に対応。
// kind: "country"（国）/ "territory"（属領・地域）。UI の絞り込みに使う。
// 手で項目を足す場合は config を直接編集してもよい（このスクリプトは初期生成・再生成用）。
//
//   node scripts/build-config.mjs           config/destinations.json を上書き
//   node scripts/build-config.mjs --check   既存 config と差分がないか確認（CI 用）

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT = path.join(__dirname, "..", "config", "destinations.json");

// [slug, name_en, name_ja, kind, aliases(; 区切り)]
// name_en は CDC 表記を素直な一般名に整えたもの。
const ROWS = [
  ["afghanistan", "Afghanistan", "アフガニスタン", "country", ""],
  ["albania", "Albania", "アルバニア", "country", ""],
  ["algeria", "Algeria", "アルジェリア", "country", ""],
  ["american-samoa", "American Samoa", "アメリカ領サモア", "territory", ""],
  ["andorra", "Andorra", "アンドラ", "country", ""],
  ["angola", "Angola", "アンゴラ", "country", ""],
  ["anguilla", "Anguilla", "アンギラ", "territory", ""],
  ["antarctica", "Antarctica", "南極", "territory", ""],
  ["antigua-and-barbuda", "Antigua and Barbuda", "アンティグア・バーブーダ", "country", ""],
  ["argentina", "Argentina", "アルゼンチン", "country", ""],
  ["armenia", "Armenia", "アルメニア", "country", ""],
  ["aruba", "Aruba", "アルバ", "territory", ""],
  ["australia", "Australia", "オーストラリア", "country", ""],
  ["austria", "Austria", "オーストリア", "country", ""],
  ["azerbaijan", "Azerbaijan", "アゼルバイジャン", "country", ""],
  ["azores", "Azores", "アゾレス諸島", "territory", "Azores Islands"],
  ["bahrain", "Bahrain", "バーレーン", "country", ""],
  ["bangladesh", "Bangladesh", "バングラデシュ", "country", ""],
  ["barbados", "Barbados", "バルバドス", "country", ""],
  ["belarus", "Belarus", "ベラルーシ", "country", ""],
  ["belgium", "Belgium", "ベルギー", "country", ""],
  ["belize", "Belize", "ベリーズ", "country", ""],
  ["benin", "Benin", "ベナン", "country", ""],
  ["bermuda", "Bermuda", "バミューダ", "territory", ""],
  ["bhutan", "Bhutan", "ブータン", "country", ""],
  ["bolivia", "Bolivia", "ボリビア", "country", ""],
  ["bonaire", "Bonaire", "ボネール", "territory", ""],
  ["bosnia-and-herzegovina", "Bosnia and Herzegovina", "ボスニア・ヘルツェゴビナ", "country", ""],
  ["botswana", "Botswana", "ボツワナ", "country", ""],
  ["brazil", "Brazil", "ブラジル", "country", ""],
  ["british-indian-ocean-territory", "British Indian Ocean Territory", "英領インド洋地域", "territory", ""],
  ["british-virgin-islands", "British Virgin Islands", "英領ヴァージン諸島", "territory", "Virgin Islands, British"],
  ["brunei", "Brunei", "ブルネイ", "country", ""],
  ["bulgaria", "Bulgaria", "ブルガリア", "country", ""],
  ["burkina-faso", "Burkina Faso", "ブルキナファソ", "country", ""],
  ["burma", "Burma (Myanmar)", "ミャンマー（ビルマ）", "country", "Myanmar;Burma"],
  ["burundi", "Burundi", "ブルンジ", "country", ""],
  ["cambodia", "Cambodia", "カンボジア", "country", ""],
  ["cameroon", "Cameroon", "カメルーン", "country", ""],
  ["canada", "Canada", "カナダ", "country", ""],
  ["canary-islands", "Canary Islands", "カナリア諸島", "territory", ""],
  ["cape-verde", "Cape Verde", "カーボベルデ", "country", "Cabo Verde"],
  ["cayman-islands", "Cayman Islands", "ケイマン諸島", "territory", ""],
  ["central-african-republic", "Central African Republic", "中央アフリカ共和国", "country", ""],
  ["chad", "Chad", "チャド", "country", ""],
  ["chile", "Chile", "チリ", "country", ""],
  ["china", "China", "中国", "country", "People's Republic of China"],
  ["christmas-island", "Christmas Island", "クリスマス島", "territory", ""],
  ["cocos-islands", "Cocos (Keeling) Islands", "ココス（キーリング）諸島", "territory", "Keeling Islands"],
  ["colombia", "Colombia", "コロンビア", "country", ""],
  ["comoros", "Comoros", "コモロ", "country", ""],
  ["congo", "Republic of the Congo", "コンゴ共和国", "country", "Congo, Republic of the;Congo-Brazzaville"],
  ["cook-islands", "Cook Islands", "クック諸島", "territory", ""],
  ["costa-rica", "Costa Rica", "コスタリカ", "country", ""],
  ["croatia", "Croatia", "クロアチア", "country", ""],
  ["cuba", "Cuba", "キューバ", "country", ""],
  ["curacao", "Curaçao", "キュラソー", "territory", "Curacao"],
  ["cyprus", "Cyprus", "キプロス", "country", ""],
  ["czechia", "Czechia", "チェコ", "country", "Czech Republic"],
  ["democratic-republic-of-congo", "Democratic Republic of the Congo", "コンゴ民主共和国", "country", "DRC;Congo-Kinshasa"],
  ["denmark", "Denmark", "デンマーク", "country", ""],
  ["djibouti", "Djibouti", "ジブチ", "country", ""],
  ["dominica", "Dominica", "ドミニカ国", "country", ""],
  ["dominican-republic", "Dominican Republic", "ドミニカ共和国", "country", ""],
  ["east-timor", "Timor-Leste (East Timor)", "東ティモール", "country", "Timor-Leste;East Timor"],
  ["easter-island", "Easter Island", "イースター島", "territory", ""],
  ["ecuador", "Ecuador", "エクアドル", "country", "Galápagos Islands"],
  ["egypt", "Egypt", "エジプト", "country", ""],
  ["el-salvador", "El Salvador", "エルサルバドル", "country", ""],
  ["equatorial-guinea", "Equatorial Guinea", "赤道ギニア", "country", ""],
  ["eritrea", "Eritrea", "エリトリア", "country", ""],
  ["estonia", "Estonia", "エストニア", "country", ""],
  ["eswatini", "Eswatini (Swaziland)", "エスワティニ（旧スワジランド）", "country", "Swaziland"],
  ["ethiopia", "Ethiopia", "エチオピア", "country", ""],
  ["falkland-islands", "Falkland Islands", "フォークランド諸島", "territory", "Islas Malvinas"],
  ["faroe-island", "Faroe Islands", "フェロー諸島", "territory", ""],
  ["fiji", "Fiji", "フィジー", "country", ""],
  ["finland", "Finland", "フィンランド", "country", ""],
  ["france", "France", "フランス", "country", ""],
  ["french-guiana", "French Guiana", "仏領ギアナ", "territory", ""],
  ["french-polynesia", "French Polynesia", "仏領ポリネシア", "territory", "Tahiti;Bora-Bora"],
  ["gabon", "Gabon", "ガボン", "country", ""],
  ["georgia", "Georgia", "ジョージア（グルジア）", "country", ""],
  ["germany", "Germany", "ドイツ", "country", ""],
  ["ghana", "Ghana", "ガーナ", "country", ""],
  ["gibraltar", "Gibraltar", "ジブラルタル", "territory", ""],
  ["greece", "Greece", "ギリシャ", "country", ""],
  ["greenland", "Greenland", "グリーンランド", "territory", ""],
  ["grenada", "Grenada", "グレナダ", "country", ""],
  ["guadeloupe", "Guadeloupe", "グアドループ", "territory", ""],
  ["guam", "Guam", "グアム", "territory", ""],
  ["guatemala", "Guatemala", "グアテマラ", "country", ""],
  ["guinea", "Guinea", "ギニア", "country", "Guinea-Conakry"],
  ["guinea-bissau", "Guinea-Bissau", "ギニアビサウ", "country", ""],
  ["guyana", "Guyana", "ガイアナ", "country", ""],
  ["haiti", "Haiti", "ハイチ", "country", ""],
  ["honduras", "Honduras", "ホンジュラス", "country", ""],
  ["hong-kong-sar", "Hong Kong", "香港", "territory", "Hong Kong SAR"],
  ["hungary", "Hungary", "ハンガリー", "country", ""],
  ["iceland", "Iceland", "アイスランド", "country", ""],
  ["india", "India", "インド", "country", ""],
  ["indonesia", "Indonesia", "インドネシア", "country", "Bali"],
  ["iran", "Iran", "イラン", "country", ""],
  ["iraq", "Iraq", "イラク", "country", ""],
  ["ireland", "Ireland", "アイルランド", "country", ""],
  ["israel", "Israel, the West Bank and Gaza", "イスラエル、ヨルダン川西岸・ガザ", "country", "Israel;West Bank;Gaza"],
  ["italy", "Italy", "イタリア", "country", "Vatican City;Holy See"],
  ["ivory-coast", "Côte d'Ivoire (Ivory Coast)", "コートジボワール", "country", "Ivory Coast;Cote d'Ivoire"],
  ["jamaica", "Jamaica", "ジャマイカ", "country", ""],
  ["japan", "Japan", "日本", "country", ""],
  ["jordan", "Jordan", "ヨルダン", "country", ""],
  ["kazakhstan", "Kazakhstan", "カザフスタン", "country", ""],
  ["kenya", "Kenya", "ケニア", "country", ""],
  ["kiribati", "Kiribati", "キリバス", "country", ""],
  ["kosovo", "Kosovo", "コソボ", "country", ""],
  ["kuwait", "Kuwait", "クウェート", "country", ""],
  ["kyrgyzstan", "Kyrgyzstan", "キルギス", "country", "Kyrgyz Republic"],
  ["laos", "Laos", "ラオス", "country", ""],
  ["latvia", "Latvia", "ラトビア", "country", ""],
  ["lebanon", "Lebanon", "レバノン", "country", ""],
  ["lesotho", "Lesotho", "レソト", "country", ""],
  ["liberia", "Liberia", "リベリア", "country", ""],
  ["libya", "Libya", "リビア", "country", ""],
  ["liechtenstein", "Liechtenstein", "リヒテンシュタイン", "country", ""],
  ["lithuania", "Lithuania", "リトアニア", "country", ""],
  ["luxembourg", "Luxembourg", "ルクセンブルク", "country", ""],
  ["macau-sar", "Macau", "マカオ", "territory", "Macao;Macau SAR"],
  ["madagascar", "Madagascar", "マダガスカル", "country", ""],
  ["madeira-islands", "Madeira Islands", "マデイラ諸島", "territory", ""],
  ["malawi", "Malawi", "マラウイ", "country", ""],
  ["malaysia", "Malaysia", "マレーシア", "country", ""],
  ["maldives", "Maldives", "モルディブ", "country", ""],
  ["mali", "Mali", "マリ", "country", ""],
  ["malta", "Malta", "マルタ", "country", ""],
  ["marshall-islands", "Marshall Islands", "マーシャル諸島", "country", ""],
  ["martinique", "Martinique", "マルティニーク", "territory", ""],
  ["mauritania", "Mauritania", "モーリタニア", "country", ""],
  ["mauritius", "Mauritius", "モーリシャス", "country", ""],
  ["mayotte", "Mayotte", "マヨット", "territory", ""],
  ["mexico", "Mexico", "メキシコ", "country", ""],
  ["micronesia", "Federated States of Micronesia", "ミクロネシア連邦", "country", "Micronesia;Yap;Chuuk;Pohnpei;Kosrae"],
  ["moldova", "Moldova", "モルドバ", "country", ""],
  ["monaco", "Monaco", "モナコ", "country", ""],
  ["mongolia", "Mongolia", "モンゴル", "country", ""],
  ["montenegro", "Montenegro", "モンテネグロ", "country", ""],
  ["montserrat", "Montserrat", "モントセラト", "territory", ""],
  ["morocco", "Morocco", "モロッコ", "country", ""],
  ["mozambique", "Mozambique", "モザンビーク", "country", ""],
  ["namibia", "Namibia", "ナミビア", "country", ""],
  ["nauru", "Nauru", "ナウル", "country", ""],
  ["nepal", "Nepal", "ネパール", "country", ""],
  ["netherlands", "The Netherlands", "オランダ", "country", "Netherlands, The;Holland"],
  ["new-caledonia", "New Caledonia", "ニューカレドニア", "territory", ""],
  ["new-zealand", "New Zealand", "ニュージーランド", "country", ""],
  ["nicaragua", "Nicaragua", "ニカラグア", "country", ""],
  ["niger", "Niger", "ニジェール", "country", ""],
  ["nigeria", "Nigeria", "ナイジェリア", "country", ""],
  ["niue", "Niue", "ニウエ", "territory", ""],
  ["norfolk-island", "Norfolk Island", "ノーフォーク島", "territory", ""],
  ["north-korea", "North Korea", "北朝鮮", "country", "DPRK"],
  ["north-macedonia", "North Macedonia", "北マケドニア", "country", "Macedonia"],
  ["northern-mariana-islands", "Northern Mariana Islands", "北マリアナ諸島", "territory", "Saipan;Tinian;Rota"],
  ["norway", "Norway", "ノルウェー", "country", ""],
  ["oman", "Oman", "オマーン", "country", ""],
  ["pakistan", "Pakistan", "パキスタン", "country", ""],
  ["palau", "Palau", "パラオ", "country", ""],
  ["panama", "Panama", "パナマ", "country", ""],
  ["papua-new-guinea", "Papua New Guinea", "パプアニューギニア", "country", ""],
  ["paraguay", "Paraguay", "パラグアイ", "country", ""],
  ["peru", "Peru", "ペルー", "country", ""],
  ["philippines", "Philippines", "フィリピン", "country", "The Philippines"],
  ["pitcairn-islands", "Pitcairn Islands", "ピトケアン諸島", "territory", ""],
  ["poland", "Poland", "ポーランド", "country", ""],
  ["portugal", "Portugal", "ポルトガル", "country", ""],
  ["puerto-rico", "Puerto Rico", "プエルトリコ", "territory", ""],
  ["qatar", "Qatar", "カタール", "country", ""],
  ["reunion", "Réunion", "レユニオン", "territory", "Reunion"],
  ["romania", "Romania", "ルーマニア", "country", ""],
  ["russia", "Russia", "ロシア", "country", "Russian Federation"],
  ["rwanda", "Rwanda", "ルワンダ", "country", ""],
  ["saba", "Saba", "サバ（オランダ領）", "territory", ""],
  ["saint-barthelemy", "Saint Barthelemy", "サン・バルテルミー", "territory", "St. Barts"],
  ["saint-helena", "Saint Helena", "セントヘレナ", "territory", ""],
  ["saint-lucia", "Saint Lucia", "セントルシア", "country", ""],
  ["saint-martin", "Saint Martin", "サン・マルタン", "territory", ""],
  ["saint-pierre-and-miquelon", "Saint Pierre and Miquelon", "サンピエール島・ミクロン島", "territory", ""],
  ["saint-vincent-and-the-grenadines", "Saint Vincent and the Grenadines", "セントビンセント及びグレナディーン諸島", "country", ""],
  ["samoa", "Samoa", "サモア", "country", ""],
  ["san-marino", "San Marino", "サンマリノ", "country", ""],
  ["sao-tome-and-principe", "São Tomé and Príncipe", "サントメ・プリンシペ", "country", "Sao Tome and Principe"],
  ["saudi-arabia", "Saudi Arabia", "サウジアラビア", "country", ""],
  ["senegal", "Senegal", "セネガル", "country", ""],
  ["serbia", "Serbia", "セルビア", "country", ""],
  ["seychelles", "Seychelles", "セーシェル", "country", ""],
  ["sierra-leone", "Sierra Leone", "シエラレオネ", "country", ""],
  ["singapore", "Singapore", "シンガポール", "country", ""],
  ["sint-eustatius", "Sint Eustatius", "シント・ユースタティウス", "territory", "Statia"],
  ["sint-maarten", "Sint Maarten", "シント・マールテン", "territory", ""],
  ["slovakia", "Slovakia", "スロバキア", "country", "Slovak Republic"],
  ["slovenia", "Slovenia", "スロベニア", "country", ""],
  ["solomon-islands", "Solomon Islands", "ソロモン諸島", "country", ""],
  ["somalia", "Somalia", "ソマリア", "country", ""],
  ["south-africa", "South Africa", "南アフリカ", "country", ""],
  ["south-georgia-south-sandwich-islands", "South Georgia and the South Sandwich Islands", "サウスジョージア・サウスサンドウィッチ諸島", "territory", ""],
  ["south-korea", "South Korea", "韓国", "country", "Republic of Korea;Korea, South"],
  ["south-sudan", "South Sudan", "南スーダン", "country", "Republic of South Sudan"],
  ["spain", "Spain", "スペイン", "country", ""],
  ["sri-lanka", "Sri Lanka", "スリランカ", "country", ""],
  ["st-kitts-and-nevis", "Saint Kitts and Nevis", "セントクリストファー・ネイビス", "country", "St. Kitts and Nevis"],
  ["sudan", "Sudan", "スーダン", "country", ""],
  ["suriname", "Suriname", "スリナム", "country", ""],
  ["sweden", "Sweden", "スウェーデン", "country", ""],
  ["switzerland", "Switzerland", "スイス", "country", ""],
  ["syria", "Syria", "シリア", "country", "Syrian Arab Republic"],
  ["taiwan", "Taiwan", "台湾", "country", ""],
  ["tajikistan", "Tajikistan", "タジキスタン", "country", ""],
  ["tanzania", "Tanzania", "タンザニア", "country", "United Republic of Tanzania;Zanzibar"],
  ["thailand", "Thailand", "タイ", "country", ""],
  ["the-bahamas", "The Bahamas", "バハマ", "country", "Bahamas, The"],
  ["the-gambia", "The Gambia", "ガンビア", "country", "Gambia, The"],
  ["togo", "Togo", "トーゴ", "country", ""],
  ["tokelau", "Tokelau", "トケラウ", "territory", ""],
  ["tonga", "Tonga", "トンガ", "country", ""],
  ["trinidad-and-tobago", "Trinidad and Tobago", "トリニダード・トバゴ", "country", ""],
  ["tunisia", "Tunisia", "チュニジア", "country", ""],
  ["turkey", "Türkiye (Turkey)", "トルコ", "country", "Turkey;Turkiye"],
  ["turkmenistan", "Turkmenistan", "トルクメニスタン", "country", ""],
  ["turks-and-caicos", "Turks and Caicos Islands", "タークス・カイコス諸島", "territory", ""],
  ["tuvalu", "Tuvalu", "ツバル", "country", ""],
  ["uganda", "Uganda", "ウガンダ", "country", ""],
  ["ukraine", "Ukraine", "ウクライナ", "country", ""],
  ["united-arab-emirates", "United Arab Emirates", "アラブ首長国連邦", "country", "UAE"],
  ["united-kingdom", "United Kingdom", "イギリス", "country", "UK;Great Britain;England;Scotland;Wales;Northern Ireland"],
  ["united-states", "United States", "アメリカ合衆国", "country", "USA;United States of America;U.S."],
  ["uruguay", "Uruguay", "ウルグアイ", "country", ""],
  ["usvirgin-islands", "U.S. Virgin Islands", "米領ヴァージン諸島", "territory", "Virgin Islands, U.S.;US Virgin Islands"],
  ["uzbekistan", "Uzbekistan", "ウズベキスタン", "country", ""],
  ["vanuatu", "Vanuatu", "バヌアツ", "country", ""],
  ["venezuela", "Venezuela", "ベネズエラ", "country", ""],
  ["vietnam", "Vietnam", "ベトナム", "country", "Viet Nam"],
  ["wake-island", "Wake Island", "ウェーク島", "territory", ""],
  ["yemen", "Yemen", "イエメン", "country", ""],
  ["zambia", "Zambia", "ザンビア", "country", ""],
  ["zimbabwe", "Zimbabwe", "ジンバブエ", "country", ""],
];

const destinations = ROWS.map(([slug, name_en, name_ja, kind, aliasesStr]) => {
  const aliases = aliasesStr ? aliasesStr.split(";").map((s) => s.trim()).filter(Boolean) : [];
  return { slug, name_en, name_ja, kind, aliases };
});

// 妥当性チェック
const slugs = new Set();
for (const d of destinations) {
  if (slugs.has(d.slug)) throw new Error(`slug 重複: ${d.slug}`);
  slugs.add(d.slug);
  if (!["country", "territory"].includes(d.kind)) throw new Error(`kind 不正: ${d.slug}`);
  if (!d.name_ja) throw new Error(`name_ja 未設定: ${d.slug}`);
}

const payload = {
  _comment:
    "CDC の目的地一覧（244件）。slug は /travel/destinations/traveler/none/<slug> に対応。" +
    "kind: country=国 / territory=属領・地域（UIの絞り込みに使用）。" +
    "生成: scripts/build-config.mjs。項目追加は本ファイル直接編集でも可。",
  counts: {
    total: destinations.length,
    country: destinations.filter((d) => d.kind === "country").length,
    territory: destinations.filter((d) => d.kind === "territory").length,
  },
  destinations,
};

const json = JSON.stringify(payload, null, 2) + "\n";

if (process.argv.includes("--check")) {
  const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : "";
  if (cur !== json) {
    console.error("config/destinations.json が build-config.mjs と一致しません。`node scripts/build-config.mjs` を実行してください。");
    process.exit(1);
  }
  console.log("OK: config は最新です。");
} else {
  fs.writeFileSync(OUT, json);
  console.log(`書き出し: ${path.relative(path.join(__dirname, ".."), OUT)}  (${payload.counts.total} 件 / 国 ${payload.counts.country} / 属領・地域 ${payload.counts.territory})`);
}
